sudo: required
services: [ docker ]
language: perl
perl: "5.18"
env:
  matrix:
    - TARGET_PLATFORM=pgxn
before_install:
  - echo $TARGET_PLATFORM > os-list.csv
install: true
script:
  - ./update_dockerfiles && git diff --exit-code dockerfiles
  - git checkout -- dockerfiles && ./update_images
  - ./ci/push_images
