name: "Release Pipeline for Pg Auto Failover"
pr: none
trigger:
  - none
jobs:

  - job: Release
    strategy:
      maxParallel: 5
      matrix:
        el8:
          TARGET_PLATFORM: el/8
          PACKAGECLOUD_API_TOKEN: 693cb52ac46e8811a0d73c8ca96d8cb1330369c4
          REPO_NAME: sample
          PKG_REPOTYPE: community
        el7:
          TARGET_PLATFORM: el/7
          PACKAGECLOUD_API_TOKEN: 693cb52ac46e8811a0d73c8ca96d8cb1330369c4
          REPO_NAME: sample
          PKG_REPOTYPE: community
    pool:
      vmImage: 'ubuntu-latest'
    container: gurkanindibay/pg-auto-failover-build:latest
    steps:
      - script: build_new_release
      - script: python upload_to_packagecloud.py $(TARGET_PLATFORM) $(PACKAGECLOUD_API_TOKEN)  $(REPO_NAME)