name: "Release Pipeline for Pg Auto Failover"
pr: none
parameters:
- name: PACKAGECLOUD_API_TOKEN
  displayName: Package Cloud API Token
  default: 0
  type: string
- name: REPO_NAME
  displayName: Repository Name
  default: sample
  values:
    - sample
    - citusdata/enterprise
    - citusdata/community
    - citusdata/community-nightlies
    - citusdata/enterprise-nightlies
    - citusdata/azure
trigger:
  - none
jobs:

  - job: Release
    strategy:
      maxParallel: 5
      matrix:
        el8:
          TARGET_PLATFORM: el/8
        el7:
          TARGET_PLATFORM: el/7
    pool:
      vmImage: 'ubuntu-latest'
    container: gurkanindibay/pg-auto-failover-build:latest
    steps:
      - script: build_new_release
      - script: python upload_to_packagecloud.py $(TARGET_PLATFORM) $(PACKAGECLOUD_API_TOKEN)  $(REPO_NAME)